using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ErrorApi.AspNetCore;

/// <summary>
/// Renders the compile-time error model as a TypeScript module: a union of every code, the status
/// each one maps to, and one alias per endpoint listing exactly the failures that endpoint can
/// produce. A client can then exhaustively switch on <c>problem.code</c> and have the compiler check it.
/// </summary>
public static class TypeScriptContractWriter
{
    /// <summary>Writes the whole contract module.</summary>
    public static string Write(IErrorApiMetadata metadata)
    {
        ArgumentNullException.ThrowIfNull(metadata);

        var errors = metadata.AllErrors.OrderBy(e => e.Code, StringComparer.Ordinal).ToList();
        var endpoints = metadata.Endpoints
            .OrderBy(e => e.RoutePattern, StringComparer.Ordinal)
            .ThenBy(e => e.HttpMethod, StringComparer.Ordinal)
            .ToList();

        var builder = new StringBuilder();
        builder.Append("// Generated by ErrorApi. Do not edit; regenerate from the API instead.\n\n");

        WriteCodes(builder, errors);
        WriteProblemShape(builder);
        WriteStatusMap(builder, errors);
        WriteEndpointAliases(builder, endpoints);
        WriteEndpointMap(builder, endpoints);

        return builder.ToString();
    }

    private static void WriteCodes(StringBuilder builder, IReadOnlyList<ErrorDescriptor> errors)
    {
        builder.Append("/** Every error code this API can return. */\nexport const API_ERROR_CODES = [\n");
        foreach (var error in errors)
        {
            builder.Append("  ").Append(Quote(error.Code)).Append(",\n");
        }

        builder.Append("] as const;\n\n");
        builder.Append("export type ApiErrorCode = (typeof API_ERROR_CODES)[number];\n\n");
    }

    private static void WriteProblemShape(StringBuilder builder) => builder.Append(
        """
        /** RFC 9457 problem document as returned by this API. */
        export interface ApiProblem<TCode extends ApiErrorCode = ApiErrorCode> {
          /** Stable machine-readable code. Switch on this, never on `title`. */
          code: TCode;
          status: number;
          title?: string;
          detail?: string;
          type?: string;
          instance?: string;
          /** Secondary failures accompanying the primary one, when the server attaches them. */
          errors?: { code: ApiErrorCode; detail?: string | null }[];
        }

        /** Narrows an unknown response body to a problem document. */
        export function isApiProblem(value: unknown): value is ApiProblem {
          return (
            typeof value === "object" &&
            value !== null &&
            typeof (value as ApiProblem).code === "string" &&
            typeof (value as ApiProblem).status === "number"
          );
        }


        """);

    private static void WriteStatusMap(StringBuilder builder, IReadOnlyList<ErrorDescriptor> errors)
    {
        builder.Append("/** HTTP status each code is returned with. */\nexport const API_ERROR_STATUS: Record<ApiErrorCode, number> = {\n");
        foreach (var error in errors)
        {
            builder.Append("  ").Append(Quote(error.Code)).Append(": ")
                   .Append(error.StatusCode.ToString(CultureInfo.InvariantCulture)).Append(",");

            var comment = error.Description ?? error.Title;
            if (!string.IsNullOrWhiteSpace(comment))
            {
                builder.Append(" // ").Append(comment!.Replace("\n", " "));
            }

            builder.Append('\n');
        }

        builder.Append("};\n\n");
    }

    private static void WriteEndpointAliases(StringBuilder builder, IReadOnlyList<EndpointErrors> endpoints)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);

        foreach (var endpoint in endpoints)
        {
            var alias = UniqueAlias(AliasFor(endpoint), used);
            builder.Append("/** Failures of `").Append(endpoint.HttpMethod).Append(' ')
                   .Append(endpoint.RoutePattern).Append("`. */\nexport type ").Append(alias).Append(" =");

            if (endpoint.Errors.Count == 0)
            {
                builder.Append(" never;\n\n");
                continue;
            }

            builder.Append('\n');
            var codes = endpoint.Errors.Select(e => e.Code).OrderBy(c => c, StringComparer.Ordinal).ToList();
            for (var i = 0; i < codes.Count; i++)
            {
                builder.Append("  | ApiProblem<").Append(Quote(codes[i])).Append('>');
                builder.Append(i == codes.Count - 1 ? ";\n\n" : "\n");
            }
        }
    }

    private static void WriteEndpointMap(StringBuilder builder, IReadOnlyList<EndpointErrors> endpoints)
    {
        builder.Append("/** Codes reachable per endpoint, keyed by `\"METHOD /route\"`. */\nexport const API_ENDPOINT_ERRORS = {\n");

        foreach (var endpoint in endpoints)
        {
            var key = endpoint.HttpMethod + " " + endpoint.RoutePattern;
            var codes = endpoint.Errors.Select(e => Quote(e.Code)).OrderBy(c => c, StringComparer.Ordinal);
            builder.Append("  ").Append(Quote(key)).Append(": [").Append(string.Join(", ", codes)).Append("],\n");
        }

        builder.Append("} as const satisfies Record<string, readonly ApiErrorCode[]>;\n");
    }

    /// <summary>Turns <c>GET /orders/{id}/lines</c> into <c>GetOrdersByIdLinesError</c>.</summary>
    private static string AliasFor(EndpointErrors endpoint)
    {
        var builder = new StringBuilder();

        foreach (var method in endpoint.HttpMethod.Split(','))
        {
            builder.Append(method == "*" ? "Any" : Pascal(method.ToLowerInvariant()));
        }

        foreach (var segment in endpoint.RoutePattern.Split('/'))
        {
            if (segment.Length == 0)
            {
                continue;
            }

            if (segment.StartsWith("{", StringComparison.Ordinal) && segment.EndsWith("}", StringComparison.Ordinal))
            {
                builder.Append("By").Append(Pascal(segment.Substring(1, segment.Length - 2)));
            }
            else
            {
                builder.Append(Pascal(segment));
            }
        }

        return builder.Append("Error").ToString();
    }

    private static string UniqueAlias(string alias, HashSet<string> used)
    {
        if (used.Add(alias))
        {
            return alias;
        }

        for (var i = 2; ; i++)
        {
            var candidate = alias + i.ToString(CultureInfo.InvariantCulture);
            if (used.Add(candidate))
            {
                return candidate;
            }
        }
    }

    private static string Pascal(string value)
    {
        var builder = new StringBuilder(value.Length);
        var upperNext = true;

        foreach (var c in value)
        {
            if (!char.IsLetterOrDigit(c))
            {
                upperNext = true;
                continue;
            }

            builder.Append(upperNext ? char.ToUpperInvariant(c) : c);
            upperNext = false;
        }

        return builder.ToString();
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
