using System.Collections.Generic;
using System.Linq;
using ErrorApi.Generator.Helpers;
using ErrorApi.Generator.Model;

namespace ErrorApi.Generator.Emit;

/// <summary>Writes the implementing half of every <c>[Error]</c>-annotated partial member.</summary>
internal static class CatalogEmitter
{
    public static IEnumerable<(string HintName, string Source)> Emit(IReadOnlyList<CatalogEntry> entries)
    {
        var groups = entries
            .Where(e => e.Kind == CatalogEntryKind.Generated)
            .GroupBy(e => (e.Namespace, Containers: string.Join("+", e.ContainerDeclarations)))
            .OrderBy(g => g.Key.Namespace, System.StringComparer.Ordinal)
            .ThenBy(g => g.Key.Containers, System.StringComparer.Ordinal);

        foreach (var group in groups)
        {
            var ordered = group.OrderBy(e => e.MemberName, System.StringComparer.Ordinal).ToList();
            yield return (HintName(ordered[0]), EmitGroup(ordered));
        }
    }

    private static string HintName(CatalogEntry entry)
    {
        var typeName = entry.ContainerDeclarations
            .Select(d => d.Split(' ').Last())
            .Aggregate((a, b) => a + "." + b)
            .Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(" ", string.Empty);

        var prefix = entry.Namespace.Length == 0 ? string.Empty : entry.Namespace + ".";
        return $"{prefix}{typeName}.Catalog.g.cs";
    }

    private static string EmitGroup(IReadOnlyList<CatalogEntry> entries)
    {
        var writer = new SourceWriter();
        GeneratedFileHeader.Write(writer);

        var scopes = new Stack<System.IDisposable>();
        var first = entries[0];

        if (first.Namespace.Length > 0)
        {
            scopes.Push(writer.Block($"namespace {first.Namespace}"));
        }

        foreach (var container in first.ContainerDeclarations)
        {
            scopes.Push(writer.Block(container));
        }

        writer.Line("/// <summary>The stable wire codes of this catalog, usable in constant patterns.</summary>");
        using (writer.Block("public static class Codes"))
        {
            foreach (var entry in entries)
            {
                writer.Line($"public const string {entry.MemberName} = {SourceWriter.Literal(entry.Code)};");
            }
        }

        foreach (var entry in entries)
        {
            writer.Line();
            WriteMember(writer, entry);
        }

        while (scopes.Count > 0)
        {
            scopes.Pop().Dispose();
        }

        return writer.ToString();
    }

    private static void WriteMember(SourceWriter writer, CatalogEntry entry)
    {
        var summary = entry.Description ?? entry.Title ?? entry.Code;
        writer.Line($"/// <summary>{Xml(summary)}</summary>");
        writer.Line($"/// <remarks>Catalog entry <c>{Xml(entry.Code)}</c>, mapped to HTTP {entry.StatusCode}.</remarks>");

        var signature = entry.IsMethod
            ? $"{entry.MemberModifiers} global::ErrorApi.Error {entry.MemberName}({Parameters(entry)})"
            : $"{entry.MemberModifiers} global::ErrorApi.Error {entry.MemberName}";

        writer.Line($"{signature}");
        writer.Line($"    => new global::ErrorApi.Error(Codes.{entry.MemberName}, {entry.StatusCode}, {SourceWriter.Literal(entry.Title)}, {DetailExpression(entry)});");
    }

    private static string Parameters(CatalogEntry entry) =>
        string.Join(", ", entry.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));

    private static string DetailExpression(CatalogEntry entry)
    {
        if (entry.Detail is null)
        {
            return "null";
        }

        if (!entry.IsMethod || entry.Parameters.Count == 0 || !entry.Detail.Contains("{"))
        {
            return SourceWriter.Literal(entry.Detail);
        }

        var arguments = string.Join(", ", entry.Parameters.Select(p => p.Name));
        return $"string.Format(global::System.Globalization.CultureInfo.InvariantCulture, {SourceWriter.Literal(entry.Detail)}, {arguments})";
    }

    private static string Xml(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}

internal static class GeneratedFileHeader
{
    public static void Write(SourceWriter writer)
    {
        writer.Line("// <auto-generated/>");
        writer.Line("// Generated by ErrorApi.Generator. Changes will be lost on the next build.");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable CS0162 // Unreachable code in generated switch tables");
        writer.Line("#pragma warning disable CS1591 // Generated members are documented inline where it helps");
        writer.Line();
    }
}
